ALTER TABLE workflow_runs ADD COLUMN IF NOT EXISTS baseline_cost_usd NUMERIC(12,6) NOT NULL DEFAULT 0;
ALTER TABLE workflow_runs ADD COLUMN IF NOT EXISTS saved_usd        NUMERIC(12,6) NOT NULL DEFAULT 0;
