# @generated by `cargo run -p tt-ts-types -- write`; DO NOT EDIT.
# These frozen dataclasses mirror structural Rust wire types. Runtime semantic
# validation, authorization, readiness, and execution remain separate gates.

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, Optional, Tuple, Union


@dataclass(frozen=True)
class AgentCostBasisApiMetered:
    amount_micros: int
    basis: Literal["api_metered"]
    evidence: ApiMeteredEvidence
    model: str
    provider: str


@dataclass(frozen=True)
class AgentCostBasisSubscription:
    basis: Literal["subscription"]
    marginal_cash_micros: int
    plan_reference: str
    vendor: str
    allocated_plan_micros: Optional[int] = None
    api_equivalent_micros: Optional[int] = None
    quota: Optional[SubscriptionQuotaEvidence] = None


@dataclass(frozen=True)
class AgentCostBasisSelfHosted:
    basis: Literal["self_hosted"]
    profile_id: str
    profile_revision: str
    energy_micros: Optional[int] = None
    hardware_amortization_micros: Optional[int] = None
    hosting_micros: Optional[int] = None
    operator_micros: Optional[int] = None


@dataclass(frozen=True)
class AgentCostBasisUnmeasured:
    basis: Literal["unmeasured"]
    expected_basis: ExpectedAgentCostBasis
    reasons: Tuple[UnmeasuredCostReason, ...]


AgentCostBasis = Union[AgentCostBasisApiMetered, AgentCostBasisSubscription, AgentCostBasisSelfHosted, AgentCostBasisUnmeasured]


AgentCostPurpose = Literal["primary_turn", "summarizer", "judge", "retry", "shadow", "validation", "embedding", "routing", "other"]


@dataclass(frozen=True)
class ApiMeteredEvidenceBilled:
    pricing_revision: str
    state: Literal["billed"]
    provider_usage_reference: Optional[str] = None


@dataclass(frozen=True)
class ApiMeteredEvidenceEstimated:
    price_observed_at: str
    pricing_revision: str
    state: Literal["estimated"]


@dataclass(frozen=True)
class ApiMeteredEvidenceInvoiceReconciled:
    invoice_reference: str
    state: Literal["invoice_reconciled"]


ApiMeteredEvidence = Union[ApiMeteredEvidenceBilled, ApiMeteredEvidenceEstimated, ApiMeteredEvidenceInvoiceReconciled]


Capability = Literal["text", "vision", "audio", "tools", "json_mode", "streaming", "reasoning", "prompt_caching"]


ExpectedAgentCostBasis = Literal["api_metered", "subscription", "self_hosted"]


SubscriptionQuotaUnit = Literal["requests", "tokens", "tool_calls", "vendor_units"]


UnmeasuredCostReasonCode = Literal["price_unknown", "provider_usage_missing", "invoice_unavailable", "subscription_quota_unavailable", "subscription_allocation_unconfigured", "local_tco_profile_missing", "local_telemetry_missing", "vendor_signal_unavailable", "other"]


@dataclass(frozen=True)
class AccessEvidence:
    reason: CapabilityReason
    state: Literal["available", "unavailable"]


@dataclass(frozen=True)
class AgentCostComponent:
    attempt: int
    component_id: str
    cost: AgentCostBasis
    purpose: AgentCostPurpose


@dataclass(frozen=True)
class CapabilityReason:
    code: str
    message: str


@dataclass(frozen=True)
class EnabledEvidence:
    reason: CapabilityReason
    source: Literal["gateway_runtime"]
    state: Literal["enabled", "disabled"]


@dataclass(frozen=True)
class FusionCapability:
    access: AccessEvidence
    current_tier: TierEvidence
    enabled: EnabledEvidence
    limits: FusionLimits
    minimum_tier: TierEvidence


@dataclass(frozen=True)
class FusionLimits:
    member_models_max: NumericLimit


@dataclass(frozen=True)
class GatewayFeatures:
    fusion: FusionCapability


@dataclass(frozen=True)
class ModelCatalogLimitations:
    fleet_consistency: Literal["not_attested"]
    provider_credentials: Literal["not_inspected"]
    provider_health: Literal["not_probed"]
    request_acceptance: Literal["not_negotiated"]


@dataclass(frozen=True)
class ModelEntry:
    id: str
    object: Literal["model"]
    owned_by: str
    tokentrimmer: ModelTokenTrimmerMeta


@dataclass(frozen=True)
class ModelPricing:
    batch_input_per_million: Optional[float]
    batch_output_per_million: Optional[float]
    cache_write_per_million: Optional[float]
    cached_input_per_million: Optional[float]
    effective_at: str
    flex_input_per_million: Optional[float]
    flex_output_per_million: Optional[float]
    input_per_million: float
    output_per_million: float
    prompt_cache_min_tokens: Optional[int]


@dataclass(frozen=True)
class ModelTokenTrimmerMeta:
    capabilities: Tuple[Capability, ...]
    max_input_tokens: int
    max_output_tokens: int
    pricing: Optional[ModelPricing]
    provider: str


@dataclass(frozen=True)
class ModelsDocumentMeta:
    limitations: ModelCatalogLimitations
    schema_version: Literal[1]
    snapshot_scope: Literal["responding_process"]
    snapshot_sha256: str
    source: Literal["registered_provider_catalog"]


@dataclass(frozen=True)
class NumericLimit:
    enforcement: Literal["gateway_runtime"]
    reason: CapabilityReason
    value: int


@dataclass(frozen=True)
class PreflightAction:
    code: Literal["choose_registered_provider_or_model", "configure_provider_credential", "retry_preflight_or_contact_operator", "change_model_or_required_capabilities", "reduce_declared_tokens_or_choose_model", "execute_request_and_handle_result"]
    reason: CapabilityReason
    required_before_request: bool


@dataclass(frozen=True)
class PreflightCostEvidence:
    input_tokens_high: Optional[int]
    input_tokens_low: Optional[int]
    output_tokens_high: Optional[int]
    output_tokens_low: Optional[int]
    reason: CapabilityReason
    source: Literal["registered_provider_pricing_catalog", "not_negotiated"]
    standard_cost_usd_high: Optional[float]
    standard_cost_usd_low: Optional[float]
    standard_input_rate_usd_per_million: Optional[float]
    standard_output_rate_usd_per_million: Optional[float]
    state: Literal["catalog_projection", "unknown"]


@dataclass(frozen=True)
class PreflightCredentialEvidence:
    reason: CapabilityReason
    source: Literal["organization_credential_store", "not_inspected"]
    state: Literal["configured", "missing", "unknown", "unavailable"]


@dataclass(frozen=True)
class PreflightLimitEvidence:
    reason: CapabilityReason
    source: Literal["registered_provider_catalog", "caller_not_supplied", "not_negotiated"]
    state: Literal["within_catalog_metadata", "exceeds_catalog_metadata", "not_evaluated", "unknown"]
    catalog_max_input_tokens: Optional[int] = None
    catalog_max_output_tokens: Optional[int] = None


@dataclass(frozen=True)
class PreflightModelSupportEvidence:
    missing_capabilities: Tuple[Capability, ...]
    reason: CapabilityReason
    source: Literal["registered_provider_catalog", "not_negotiated"]
    state: Literal["supported_by_catalog", "unsupported_by_catalog", "unknown"]


@dataclass(frozen=True)
class PreflightProviderResolution:
    reason: CapabilityReason
    source: Literal["registered_provider_catalog", "gateway_dispatch_resolution", "gateway_runtime"]
    state: Literal["exact_catalog_match", "provider_registered_catalog_miss", "provider_unregistered", "dispatch_resolved_catalog_unknown", "unresolved"]
    provider: Optional[str] = None


@dataclass(frozen=True)
class RequestPreflightBatchRequest:
    requests: Tuple[RequestPreflightRequest, ...]
    schema_version: Literal[1]


@dataclass(frozen=True)
class RequestPreflightRequest:
    model: str
    required_capabilities: Tuple[Capability, ...]
    schema_version: Literal[1]
    declared_input_tokens: Optional[int] = None
    provider: Optional[str] = None
    requested_max_output_tokens: Optional[int] = None


@dataclass(frozen=True)
class SchemaVersionEvidence:
    reason: CapabilityReason
    source: Literal["gateway_runtime"]
    state: Literal["known", "unversioned"]
    version: Optional[int]


@dataclass(frozen=True)
class SchemaVersions:
    capabilities_document: SchemaVersionEvidence
    fusion_request: SchemaVersionEvidence


@dataclass(frozen=True)
class SubscriptionQuotaEvidence:
    source: str
    unit: SubscriptionQuotaUnit
    used: int
    limit: Optional[int] = None
    window_ends_at: Optional[str] = None


@dataclass(frozen=True)
class TierEvidence:
    reason: CapabilityReason
    source: Literal["authenticated_api_key", "gateway_free_default", "gateway_runtime"]
    state: Literal["known"]
    value: Literal["free", "pro", "team", "scale"]


@dataclass(frozen=True)
class UnknownEvidence:
    reason: CapabilityReason
    source: Literal["not_negotiated"]
    state: Literal["unknown"]


@dataclass(frozen=True)
class UnmeasuredCostReason:
    code: UnmeasuredCostReasonCode
    detail: Optional[str] = None


@dataclass(frozen=True)
class ModelsResponse:
    data: Tuple[ModelEntry, ...]
    object: Literal["list"]
    tokentrimmer: ModelsDocumentMeta


@dataclass(frozen=True)
class GatewayCapabilitiesDocument:
    features: GatewayFeatures
    generated_at: str
    modality_support: UnknownEvidence
    model_support: UnknownEvidence
    provider_credentials: UnknownEvidence
    provider_health: UnknownEvidence
    schema_version: Literal[1]
    schema_versions: SchemaVersions
    scope: Literal["gateway_runtime"]
    snapshot_scope: Literal["responding_process"]


@dataclass(frozen=True)
class RequestPreflightResponse:
    actions: Tuple[PreflightAction, ...]
    catalog_cost: PreflightCostEvidence
    catalog_limits: PreflightLimitEvidence
    credential: PreflightCredentialEvidence
    generated_at: str
    model_support: PreflightModelSupportEvidence
    provider_health: UnknownEvidence
    provider_resolution: PreflightProviderResolution
    request: RequestPreflightRequest
    request_acceptance: UnknownEvidence
    schema_version: Literal[1]
    scope: Literal["request_preflight"]
    snapshot_scope: Literal["responding_process"]


@dataclass(frozen=True)
class RequestPreflightBatchResponse:
    documents: Tuple[RequestPreflightResponse, ...]
    generated_at: str
    limitations: Tuple[CapabilityReason, ...]
    request: RequestPreflightBatchRequest
    schema_version: Literal[1]
    scope: Literal["request_preflight_batch"]
    snapshot_scope: Literal["responding_process"]


@dataclass(frozen=True)
class AgentRunCostEvidence:
    components: Tuple[AgentCostComponent, ...]
    run_id: str
    schema_version: Literal[1]

