#!/usr/bin/env bash
# context-map.sh — regenerate .claude/INDEX.md with structural facts about the repo.
#
# Pairs with .claude/CONTEXT_MAP.md (the human-curated editorial map):
#   - CONTEXT_MAP.md says "what matters for which tasks" (rarely changes)
#   - INDEX.md is the auto-generated facts: pub symbols, dep graph, hotspots
#
# Run weekly (cron-friendly) or on demand: `make context-index`.
set -euo pipefail

cd "$(dirname "$0")/.."

INDEX=".claude/INDEX.md"
TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)

mkdir -p .claude

{
  echo "# Repo structural index"
  echo
  echo "_Auto-generated by \`scripts/context-map.sh\` at ${TS}. Do not hand-edit — re-run instead._"
  echo
  echo "Editorial counterpart: \`.claude/CONTEXT_MAP.md\` (curated, hand-edited)."
  echo

  # --- Crates ---
  echo "## Workspace crates"
  echo
  echo "| Crate | Path | Description |"
  echo "|---|---|---|"
  while IFS= read -r cargo_toml; do
    name=$(grep -E '^name' "$cargo_toml" | head -1 | sed -E 's/name[[:space:]]*=[[:space:]]*"([^"]+)".*/\1/')
    desc=$(grep -E '^description' "$cargo_toml" | head -1 | sed -E 's/description[[:space:]]*=[[:space:]]*"([^"]+)".*/\1/' || echo "")
    dir=$(dirname "$cargo_toml")
    echo "| \`${name}\` | \`${dir}\` | ${desc:-(no description)} |"
  done < <(find crates -name Cargo.toml -not -path '*/target/*' | sort)
  echo

  # --- Public symbols per crate ---
  echo "## Public surface — top-level pub items per crate"
  echo
  while IFS= read -r src_dir; do
    crate_root=$(dirname "$src_dir")
    crate_name=$(grep -E '^name' "$crate_root/Cargo.toml" | head -1 | sed -E 's/name[[:space:]]*=[[:space:]]*"([^"]+)".*/\1/')
    pubs=$(grep -rnE '^[[:space:]]*pub[[:space:]]+(struct|enum|trait|fn|type|mod|use|const)[[:space:]]+' \
      --include='*.rs' "$src_dir" 2>/dev/null \
      | head -25 \
      | sed -E "s|^${src_dir}/(.+):([0-9]+):(.*)|- \`${crate_root}/src/\1:\2\` \`\3\`|" \
      || true)
    if [[ -n "${pubs}" ]]; then
      echo "### \`${crate_name}\`"
      echo
      printf '%s\n' "${pubs}"
      echo
    fi
  done < <(find crates -type d -name src -not -path '*/target/*' | sort)

  # --- Hotspots: files touched recently ---
  echo "## Recently touched files (last 30 days)"
  echo
  if [[ -d .git ]] && git log -1 >/dev/null 2>&1; then
    hot=$(git log --since="30 days ago" --name-only --pretty=format: 2>/dev/null \
      | grep -v '^$' \
      | sort \
      | uniq -c \
      | sort -rn \
      | head -15 \
      | awk '{printf "| %s | %d |\n", $2, $1}')
    if [[ -n "${hot}" ]]; then
      echo "| File | Commit touches |"
      echo "|---|---|"
      printf '%s\n' "${hot}"
    else
      echo "_(no recent commits — pre-first-commit state.)_"
    fi
  else
    echo "_(no git history yet.)_"
  fi
  echo

  # --- Doc inventory ---
  echo "## Docs"
  echo
  echo "| Path | Size | Use for |"
  echo "|---|---|---|"
  for f in docs/*.md; do
    [[ -f "$f" ]] || continue
    size=$(wc -c < "$f" | tr -d ' ')
    use=""
    case "$(basename "$f")" in
      tokentrimmer-architecture-spec-v1.md) use="System-wide overview — anti-context for routine tasks." ;;
      01-inspect-rule-catalog.md) use="Writing or reasoning about Inspect rules." ;;
      02-provider-adapter-guide.md) use="Implementing a Provider adapter (Anthropic worked example)." ;;
      03-plan-replay-design.md) use="Touching the Plan replay engine or reconciliation." ;;
      04-gateway-api-reference.md) use="Changing the public HTTP API surface." ;;
      *) use="(uncategorized)" ;;
    esac
    echo "| \`$f\` | ${size}B | ${use} |"
  done
  echo

  # --- Doc/code cross-references ---
  echo "## Files that reference docs/ specs"
  echo
  refs=$(grep -rln --include='*.rs' --include='*.md' --exclude-dir=target \
    -E 'docs/(0[0-9]-[a-z-]+|tokentrimmer-)' . 2>/dev/null | sort -u || true)
  if [[ -n "${refs}" ]]; then
    printf '%s\n' "${refs}" | sed 's/^/- `/;s/$/`/'
  else
    echo "_(none yet)_"
  fi
  echo

} > "${INDEX}"

echo "Wrote ${INDEX} ($(wc -l < "${INDEX}") lines)"
