// @generated by `cargo run -p tt-ts-types -- write`; DO NOT EDIT.
// These are structural Rust wire types. Runtime semantic validation, safe-integer
// checks, authorization, readiness, and execution remain separate gates.

export type AccessEvidence = {
  reason: CapabilityReason;
  state: "available" | "unavailable";
};

export type AgenticBudget = {
  cache_prefix?: boolean;
  clear_at_least_tokens?: number;
  elide_stale_tools?: boolean;
  keep_recent_pairs?: number;
  route_mechanical_to?: string | null;
  semantic_substep_cache?: boolean;
};

export type BudgetPolicy = {
  max_cost_usd?: number | null;
  on_exceed?: OnExceed;
};

export type CapabilityReason = {
  code: string;
  message: string;
};

export type DocumentSource = {
  type: "url";
  url: string;
} | {
  data: string;
  media_type: string;
  type: "base64";
};

export type Edge = {
  from: string;
  map?: string | null;
  to: string;
};

export type EnabledEvidence = {
  reason: CapabilityReason;
  source: "gateway_runtime";
  state: "enabled" | "disabled";
};

export type FusionCapability = {
  access: AccessEvidence;
  current_tier: TierEvidence;
  enabled: EnabledEvidence;
  limits: FusionLimits;
  minimum_tier: TierEvidence;
};

export type FusionLimits = {
  member_models_max: NumericLimit;
};

export type GatewayFeatures = {
  fusion: FusionCapability;
};

export type ModelSelection = {
  model: string;
  type: "model";
} | {
  route_ref: string;
  type: "route";
} | {
  type: "auto";
};

export type Node = {
  id: string;
} & ({
  type: "trigger";
} | {
  max_cost_usd?: number | null;
  max_output_tokens?: number | null;
  prompt: string;
  selection: ModelSelection;
  type: "model";
} | {
  max_cost_usd?: number | null;
  max_output_tokens?: number | null;
  max_turns?: number | null;
  prompt: string;
  selection: ModelSelection;
  tools?: Array<Tool>;
  type: "agent";
} | {
  expr: string;
  type: "transform";
} | {
  cond: string;
  type: "branch";
  when_false: string;
  when_true: string;
} | {
  type: "output";
} | {
  body?: string | null;
  headers?: Array<[string, string]>;
  max_response_bytes?: number | null;
  method: string;
  type: "http";
  url: string;
} | {
  type: "sub_workflow";
  version?: number | null;
  workflow_id: string;
} | {
  body_workflow_id: string;
  cond: string;
  max_iters?: number;
  type: "loop";
} | {
  cache_key?: string | null;
  source: DocumentSource;
  type: "document";
});

export type NumericLimit = {
  enforcement: "gateway_runtime";
  reason: CapabilityReason;
  value: number;
};

export type OnExceed = "Stop";

export type RouteAction = {
  agentic_budget?: AgenticBudget | null;
  auto_pause?: boolean;
  batch?: boolean;
  compress?: boolean;
  content_compress?: boolean;
  diff?: boolean;
  disable_cache?: boolean;
  doc_compaction?: boolean;
  document_lane?: boolean;
  fallbacks?: Array<string>;
  flex?: boolean;
  format_switch?: string | null;
  max_cost_usd?: number | null;
  minify_json?: boolean;
  panel?: RoutePanel | null;
  pause_floor_pass_rate?: number | null;
  pause_min_verdicts?: number | null;
  reasoning_budget_tokens?: number | null;
  reasoning_max_effort?: string | null;
  redact?: boolean;
  shadow_model?: string | null;
  target_model?: string | null;
  traffic_pct?: number | null;
  workflow?: RouteWorkflow | null;
};

export type RouteConditions = {
  content_type?: string | null;
  estimated_cost_gt?: number | null;
  estimated_cost_lt?: number | null;
  has_audio?: boolean | null;
  has_documents?: boolean | null;
  has_images?: boolean | null;
  input_tokens_gt?: number | null;
  input_tokens_lt?: number | null;
  model_in?: Array<string>;
  not_reasoning_class?: boolean;
  prompt_contains_any_of?: Array<string>;
  tag_equals?: string | null;
  upstream_latency_ms_p95_gt?: number | null;
};

export type RoutePanel = {
  arbiter?: string | null;
  max_cost_usd?: number | null;
  members?: Array<string>;
  quorum?: number | null;
  strategy: string;
};

export type RouteWorkflow = {
  environment?: RouteWorkflowEnvironment | null;
  max_cost_usd?: number | null;
  mode?: string | null;
  workflow_id: string;
};

export type RouteWorkflowEnvironment = "development" | "staging" | "production";

export type SchemaVersionEvidence = {
  reason: CapabilityReason;
  source: "gateway_runtime";
  state: "known" | "unversioned";
  version?: number | null;
};

export type SchemaVersions = {
  capabilities_document: SchemaVersionEvidence;
  fusion_request: SchemaVersionEvidence;
};

export type TierEvidence = {
  reason: CapabilityReason;
  source: "authenticated_api_key" | "gateway_free_default" | "gateway_runtime";
  state: "known";
  value: "free" | "pro" | "team" | "scale";
};

export type Tool = {
  function: ToolFunction;
  type: string;
};

export type ToolFunction = {
  description?: string | null;
  name: string;
  parameters: unknown;
};

export type UnknownEvidence = {
  reason: CapabilityReason;
  source: "not_negotiated";
  state: "unknown";
};

export type WorkflowTrigger = {
  environment?: WorkflowTriggerEnvironment | null;
  interval: string;
  type: "schedule";
} | {
  environment?: WorkflowTriggerEnvironment | null;
  token_id: string;
  type: "webhook";
};

export type WorkflowTriggerEnvironment = "development" | "staging" | "production";

export type RouteWriteRequest = {
  enabled?: boolean;
  name: string;
  priority?: number;
  schema_version?: 1 | null;
  then: RouteAction;
  when?: RouteConditions;
};

export type WorkflowDefinition = {
  allowed_hosts?: Array<string>;
  budget?: BudgetPolicy;
  edges: Array<Edge>;
  id: string;
  inputs?: unknown;
  metadata?: unknown;
  name: string;
  nodes: Array<Node>;
  triggers?: Array<WorkflowTrigger>;
  version: number;
};

export type WorkflowWriteRequest = {
  allowed_hosts?: Array<string>;
  budget?: BudgetPolicy;
  edges: Array<Edge>;
  expected_latest_version?: number | null;
  id?: string | null;
  inputs?: unknown;
  metadata?: unknown;
  name: string;
  nodes: Array<Node>;
  triggers?: Array<WorkflowTrigger>;
  version?: number | null;
};

export type GatewayCapabilitiesDocument = {
  features: GatewayFeatures;
  generated_at: string;
  modality_support: UnknownEvidence;
  model_support: UnknownEvidence;
  provider_credentials: UnknownEvidence;
  provider_health: UnknownEvidence;
  schema_version: 1;
  schema_versions: SchemaVersions;
  scope: "gateway_runtime";
  snapshot_scope: "responding_process";
};
