// @generated by `cargo run -p tt-ts-types -- write`; DO NOT EDIT.
// These are structural Rust wire types. Runtime semantic validation, safe-integer
// checks, authorization, readiness, and execution remain separate gates.

export type AccessEvidence = {
  reason: CapabilityReason;
  state: "available" | "unavailable";
};

export type AgentCostBasis = {
  amount_micros: number;
  basis: "api_metered";
  evidence: ApiMeteredEvidence;
  model: string;
  provider: string;
} | {
  allocated_plan_micros?: number | null;
  api_equivalent_micros?: number | null;
  basis: "subscription";
  marginal_cash_micros: number;
  plan_reference: string;
  quota?: SubscriptionQuotaEvidence | null;
  vendor: string;
} | {
  basis: "self_hosted";
  energy_micros?: number | null;
  hardware_amortization_micros?: number | null;
  hosting_micros?: number | null;
  operator_micros?: number | null;
  profile_id: string;
  profile_revision: string;
} | {
  basis: "unmeasured";
  expected_basis: ExpectedAgentCostBasis;
  reasons: Array<UnmeasuredCostReason>;
};

export type AgentCostComponent = {
  attempt: number;
  component_id: string;
  cost: AgentCostBasis;
  purpose: AgentCostPurpose;
};

export type AgentCostPurpose = "primary_turn" | "summarizer" | "judge" | "retry" | "shadow" | "validation" | "embedding" | "routing" | "other";

export type AgenticBudget = {
  cache_prefix?: boolean;
  clear_at_least_tokens?: number;
  elide_stale_tools?: boolean;
  keep_recent_pairs?: number;
  route_mechanical_to?: string | null;
  semantic_substep_cache?: boolean;
};

export type ApiMeteredEvidence = {
  pricing_revision: string;
  provider_usage_reference?: string | null;
  state: "billed";
} | {
  price_observed_at: string;
  pricing_revision: string;
  state: "estimated";
} | {
  invoice_reference: string;
  state: "invoice_reconciled";
};

export type BudgetPolicy = {
  max_cost_usd?: number | null;
  on_exceed?: OnExceed;
};

export type Capability = "text" | "vision" | "audio" | "tools" | "json_mode" | "streaming" | "reasoning" | "prompt_caching";

export type CapabilityReason = {
  code: string;
  message: string;
};

export type DocumentSource = {
  type: "url";
  url: string;
} | {
  data: string;
  media_type: string;
  type: "base64";
};

export type Edge = {
  from: string;
  map?: string | null;
  to: string;
};

export type EnabledEvidence = {
  reason: CapabilityReason;
  source: "gateway_runtime";
  state: "enabled" | "disabled";
};

export type ExpectedAgentCostBasis = "api_metered" | "subscription" | "self_hosted";

export type FusionCapability = {
  access: AccessEvidence;
  current_tier: TierEvidence;
  enabled: EnabledEvidence;
  limits: FusionLimits;
  minimum_tier: TierEvidence;
};

export type FusionLimits = {
  member_models_max: NumericLimit;
};

export type GatewayFeatures = {
  fusion: FusionCapability;
};

export type ModelCatalogLimitations = {
  fleet_consistency: "not_attested";
  provider_credentials: "not_inspected";
  provider_health: "not_probed";
  request_acceptance: "not_negotiated";
};

export type ModelEntry = {
  id: string;
  object: "model";
  owned_by: string;
  tokentrimmer: ModelTokenTrimmerMeta;
};

export type ModelPricing = {
  batch_input_per_million: number | null;
  batch_output_per_million: number | null;
  cache_write_per_million: number | null;
  cached_input_per_million: number | null;
  effective_at: string;
  flex_input_per_million: number | null;
  flex_output_per_million: number | null;
  input_per_million: number;
  output_per_million: number;
  prompt_cache_min_tokens: number | null;
};

export type ModelSelection = {
  model: string;
  type: "model";
} | {
  route_ref: string;
  type: "route";
} | {
  type: "auto";
};

export type ModelTokenTrimmerMeta = {
  capabilities: Array<Capability>;
  max_input_tokens: number;
  max_output_tokens: number;
  pricing: ModelPricing | null;
  provider: string;
};

export type ModelsDocumentMeta = {
  limitations: ModelCatalogLimitations;
  schema_version: 1;
  snapshot_scope: "responding_process";
  snapshot_sha256: string;
  source: "registered_provider_catalog";
};

export type Node = {
  id: string;
} & ({
  type: "trigger";
} | {
  max_cost_usd?: number | null;
  max_output_tokens?: number | null;
  prompt: string;
  selection: ModelSelection;
  type: "model";
} | {
  max_cost_usd?: number | null;
  max_output_tokens?: number | null;
  max_turns?: number | null;
  prompt: string;
  selection: ModelSelection;
  tools?: Array<Tool>;
  type: "agent";
} | {
  expr: string;
  type: "transform";
} | {
  cond: string;
  type: "branch";
  when_false: string;
  when_true: string;
} | {
  type: "output";
} | {
  body?: string | null;
  headers?: Array<[string, string]>;
  max_response_bytes?: number | null;
  method: string;
  type: "http";
  url: string;
} | {
  type: "sub_workflow";
  version?: number | null;
  workflow_id: string;
} | {
  body_workflow_id: string;
  cond: string;
  max_iters?: number;
  type: "loop";
} | {
  cache_key?: string | null;
  source: DocumentSource;
  type: "document";
});

export type NumericLimit = {
  enforcement: "gateway_runtime";
  reason: CapabilityReason;
  value: number;
};

export type OnExceed = "Stop";

export type PreflightAction = {
  code: "choose_registered_provider_or_model" | "configure_provider_credential" | "retry_preflight_or_contact_operator" | "change_model_or_required_capabilities" | "reduce_declared_tokens_or_choose_model" | "execute_request_and_handle_result";
  reason: CapabilityReason;
  required_before_request: boolean;
};

export type PreflightCostEvidence = {
  input_tokens_high: number | null;
  input_tokens_low: number | null;
  output_tokens_high: number | null;
  output_tokens_low: number | null;
  reason: CapabilityReason;
  source: "registered_provider_pricing_catalog" | "not_negotiated";
  standard_cost_usd_high: number | null;
  standard_cost_usd_low: number | null;
  standard_input_rate_usd_per_million: number | null;
  standard_output_rate_usd_per_million: number | null;
  state: "catalog_projection" | "unknown";
};

export type PreflightCredentialEvidence = {
  reason: CapabilityReason;
  source: "organization_credential_store" | "not_inspected";
  state: "configured" | "missing" | "unknown" | "unavailable";
};

export type PreflightLimitEvidence = {
  catalog_max_input_tokens?: number | null;
  catalog_max_output_tokens?: number | null;
  reason: CapabilityReason;
  source: "registered_provider_catalog" | "caller_not_supplied" | "not_negotiated";
  state: "within_catalog_metadata" | "exceeds_catalog_metadata" | "not_evaluated" | "unknown";
};

export type PreflightModelSupportEvidence = {
  missing_capabilities: Array<Capability>;
  reason: CapabilityReason;
  source: "registered_provider_catalog" | "not_negotiated";
  state: "supported_by_catalog" | "unsupported_by_catalog" | "unknown";
};

export type PreflightProviderResolution = {
  provider?: string | null;
  reason: CapabilityReason;
  source: "registered_provider_catalog" | "gateway_dispatch_resolution" | "gateway_runtime";
  state: "exact_catalog_match" | "provider_registered_catalog_miss" | "provider_unregistered" | "dispatch_resolved_catalog_unknown" | "unresolved";
};

export type RequestPreflightBatchRequest = {
  requests: Array<RequestPreflightRequest>;
  schema_version: 1;
};

export type RequestPreflightRequest = {
  declared_input_tokens?: number | null;
  model: string;
  provider?: string | null;
  requested_max_output_tokens?: number | null;
  required_capabilities: Array<Capability>;
  schema_version: 1;
};

export type RouteAction = {
  agentic_budget?: AgenticBudget | null;
  auto_pause?: boolean;
  batch?: boolean;
  compress?: boolean;
  content_compress?: boolean;
  diff?: boolean;
  disable_cache?: boolean;
  doc_compaction?: boolean;
  document_lane?: boolean;
  fallbacks?: Array<string>;
  flex?: boolean;
  format_switch?: string | null;
  max_cost_usd?: number | null;
  minify_json?: boolean;
  panel?: RoutePanel | null;
  pause_floor_pass_rate?: number | null;
  pause_min_verdicts?: number | null;
  reasoning_budget_tokens?: number | null;
  reasoning_max_effort?: string | null;
  redact?: boolean;
  shadow_model?: string | null;
  target_model?: string | null;
  traffic_pct?: number | null;
  workflow?: RouteWorkflow | null;
};

export type RouteConditions = {
  content_type?: string | null;
  estimated_cost_gt?: number | null;
  estimated_cost_lt?: number | null;
  has_audio?: boolean | null;
  has_documents?: boolean | null;
  has_images?: boolean | null;
  input_tokens_gt?: number | null;
  input_tokens_lt?: number | null;
  model_in?: Array<string>;
  not_reasoning_class?: boolean;
  prompt_contains_any_of?: Array<string>;
  tag_equals?: string | null;
  upstream_latency_ms_p95_gt?: number | null;
};

export type RoutePanel = {
  arbiter?: string | null;
  max_cost_usd?: number | null;
  members?: Array<string>;
  quorum?: number | null;
  strategy: string;
};

export type RouteWorkflow = {
  environment?: RouteWorkflowEnvironment | null;
  max_cost_usd?: number | null;
  mode?: string | null;
  workflow_id: string;
};

export type RouteWorkflowEnvironment = "development" | "staging" | "production";

export type SchemaVersionEvidence = {
  reason: CapabilityReason;
  source: "gateway_runtime";
  state: "known" | "unversioned";
  version: number | null;
};

export type SchemaVersions = {
  capabilities_document: SchemaVersionEvidence;
  fusion_request: SchemaVersionEvidence;
};

export type SubscriptionQuotaEvidence = {
  limit?: number | null;
  source: string;
  unit: SubscriptionQuotaUnit;
  used: number;
  window_ends_at?: string | null;
};

export type SubscriptionQuotaUnit = "requests" | "tokens" | "tool_calls" | "vendor_units";

export type TierEvidence = {
  reason: CapabilityReason;
  source: "authenticated_api_key" | "gateway_free_default" | "gateway_runtime";
  state: "known";
  value: "free" | "pro" | "team" | "scale";
};

export type Tool = {
  function: ToolFunction;
  type: string;
};

export type ToolFunction = {
  description?: string | null;
  name: string;
  parameters: unknown;
};

export type UnknownEvidence = {
  reason: CapabilityReason;
  source: "not_negotiated";
  state: "unknown";
};

export type UnmeasuredCostReason = {
  code: UnmeasuredCostReasonCode;
  detail?: string | null;
};

export type UnmeasuredCostReasonCode = "price_unknown" | "provider_usage_missing" | "invoice_unavailable" | "subscription_quota_unavailable" | "subscription_allocation_unconfigured" | "local_tco_profile_missing" | "local_telemetry_missing" | "vendor_signal_unavailable" | "other";

export type WorkflowTrigger = {
  environment?: WorkflowTriggerEnvironment | null;
  interval: string;
  type: "schedule";
} | {
  environment?: WorkflowTriggerEnvironment | null;
  token_id: string;
  type: "webhook";
};

export type WorkflowTriggerEnvironment = "development" | "staging" | "production";

export type RouteWriteRequest = {
  enabled?: boolean;
  name: string;
  priority?: number;
  schema_version?: 1 | null;
  then: RouteAction;
  when?: RouteConditions;
};

export type WorkflowDefinition = {
  allowed_hosts?: Array<string>;
  budget?: BudgetPolicy;
  edges: Array<Edge>;
  id: string;
  inputs?: unknown;
  metadata?: unknown;
  name: string;
  nodes: Array<Node>;
  triggers?: Array<WorkflowTrigger>;
  version: number;
};

export type WorkflowWriteRequest = {
  allowed_hosts?: Array<string>;
  budget?: BudgetPolicy;
  edges: Array<Edge>;
  expected_latest_version?: number | null;
  id?: string | null;
  inputs?: unknown;
  metadata?: unknown;
  name: string;
  nodes: Array<Node>;
  triggers?: Array<WorkflowTrigger>;
  version?: number | null;
};

export type ModelsResponse = {
  data: Array<ModelEntry>;
  object: "list";
  tokentrimmer: ModelsDocumentMeta;
};

export type GatewayCapabilitiesDocument = {
  features: GatewayFeatures;
  generated_at: string;
  modality_support: UnknownEvidence;
  model_support: UnknownEvidence;
  provider_credentials: UnknownEvidence;
  provider_health: UnknownEvidence;
  schema_version: 1;
  schema_versions: SchemaVersions;
  scope: "gateway_runtime";
  snapshot_scope: "responding_process";
};

export type RequestPreflightResponse = {
  actions: Array<PreflightAction>;
  catalog_cost: PreflightCostEvidence;
  catalog_limits: PreflightLimitEvidence;
  credential: PreflightCredentialEvidence;
  generated_at: string;
  model_support: PreflightModelSupportEvidence;
  provider_health: UnknownEvidence;
  provider_resolution: PreflightProviderResolution;
  request: RequestPreflightRequest;
  request_acceptance: UnknownEvidence;
  schema_version: 1;
  scope: "request_preflight";
  snapshot_scope: "responding_process";
};

export type RequestPreflightBatchResponse = {
  documents: Array<RequestPreflightResponse>;
  generated_at: string;
  limitations: Array<CapabilityReason>;
  request: RequestPreflightBatchRequest;
  schema_version: 1;
  scope: "request_preflight_batch";
  snapshot_scope: "responding_process";
};

export type AgentRunCostEvidence = {
  components: Array<AgentCostComponent>;
  run_id: string;
  schema_version: 1;
};
