// @generated by `cargo run -p tt-ts-types -- write`; DO NOT EDIT.
// JSON integer fields are `number` here. Runtime consumers must retain their
// existing Number.isSafeInteger checks before cryptographic verification.

export type Actor = {
  type: "user";
  user_id: string;
} | {
  key_id: string;
  type: "api_key";
} | {
  type: "system";
} | {
  type: "anonymous";
};

export type AgenticBudget = {
  cache_prefix?: boolean;
  clear_at_least_tokens?: number;
  elide_stale_tools?: boolean;
  keep_recent_pairs?: number;
  route_mechanical_to?: string | null;
  semantic_substep_cache?: boolean;
};

export type Aggregates = {
  cache_hit_rate_projected: number;
  l2_per_class?: Array<PerClassL2Metrics>;
  l2_poisoning_candidates?: number;
  l2_projections?: Array<L2Projection>;
  p50_latency_ms_projected: number;
  p95_latency_ms_projected: number;
  projected_savings_pct: number;
  projected_savings_usd: number;
  requests_rerouted: number;
  requests_unchanged: number;
  requests_unprice_able: number;
  total_baseline_cost_usd: number;
  total_projected_cost_usd: number;
};

export type AuditEntry = {
  actor: Actor;
  event: string;
  hash: string;
  id: string;
  org_id: string;
  payload: unknown;
  prev_hash: string;
  seq: number;
  signature: string;
  timestamp: string;
};

export type BundleAttestation = {
  entries: Array<AuditEntry>;
  verifying_key: string;
};

export type ConfidenceIntervals = {
  cache_hit_rate_95: [number, number];
  p50_latency_ms_95?: [number, number];
  p95_latency_ms_95?: [number, number];
  savings_pct_95: [number, number];
  savings_usd_95: [number, number];
};

export type JudgeVerdict = "acceptable" | "degraded" | "unclear";

export type L2Projection = {
  poisoning_candidates?: number;
  projected_l2_hit_rate: number;
  projected_l2_hits: number;
  threshold: number;
  total: number;
};

export type L2TaskClass = "chat_completions";

export type ModelPricing = {
  batch_input_per_million?: number | null;
  batch_output_per_million?: number | null;
  cached_input_per_million?: number | null;
  flex_input_per_million?: number | null;
  flex_output_per_million?: number | null;
  input_per_million: number;
  output_per_million: number;
};

export type PerClassL2Metrics = {
  considered: number;
  hits: number;
  misses: number;
  poisoning_candidates: number;
  task_class: L2TaskClass;
};

export type PerRouteBreakdown = {
  baseline_cost_usd: number;
  matched: number;
  projected_cost_usd: number;
  route_id: string;
  route_name: string;
  savings_usd: number;
};

export type PlanConfig = {
  l1_ttl_seconds?: number | null;
  l2_threshold_sweep?: Array<number>;
  l2_ttl_seconds?: number | null;
};

export type PlanInput = {
  bootstrap_iterations: number;
  config?: PlanConfig;
  org_id: string;
  plan_id: string;
  pricing: Record<string, ModelPricing>;
  proposed_routes: Array<ProposedRoute>;
  requests: Array<RequestLog>;
  seed: number;
  window_end: string;
  window_start: string;
};

export type PlanResult = {
  aggregates: Aggregates;
  caveats: Array<string>;
  confidence_intervals: ConfidenceIntervals;
  org_id: string;
  per_route_breakdown: Array<PerRouteBreakdown>;
  plan_id: string;
  proposed_routes?: Array<ProposedRoute>;
  quality?: QualityResult | null;
  sample_size: number;
  window_end: string;
  window_start: string;
};

export type ProposedRoute = {
  enabled: boolean;
  id: string;
  name: string;
  priority: number;
  then: RouteAction;
  when: RouteConditions;
};

export type QualityResult = {
  acceptable_count: number;
  caveats: Array<string>;
  degraded_count: number;
  degraded_pct: number;
  risk_band: RiskBand;
  sample_size: number;
  sampled_examples: Array<SampleScore>;
  unclear_count: number;
};

export type RequestLog = {
  baseline_cost_usd: number;
  body?: string | null;
  cache_layer?: string | null;
  cached: boolean;
  cached_tokens: number;
  cost_usd: number;
  diff_saved_usd?: number | null;
  embedding?: Array<number> | null;
  finish_reason?: string | null;
  id: string;
  input_tokens: number;
  latency_ms: number;
  matched_route_id?: string | null;
  minify_saved_est_usd?: number | null;
  model: string;
  org_id: string;
  output_tokens: number;
  provider: string;
  requested_model?: string | null;
  response_body?: string | null;
  status: number;
  tag?: string | null;
  task_class?: L2TaskClass;
  ts: string;
  upstream_latency_ms?: number | null;
};

export type RiskBand = "low" | "medium" | "high";

export type RouteAction = {
  agentic_budget?: AgenticBudget | null;
  auto_pause?: boolean;
  batch?: boolean;
  compress?: boolean;
  content_compress?: boolean;
  diff?: boolean;
  disable_cache?: boolean;
  doc_compaction?: boolean;
  document_lane?: boolean;
  fallbacks?: Array<string>;
  flex?: boolean;
  format_switch?: string | null;
  max_cost_usd?: number | null;
  minify_json?: boolean;
  panel?: RoutePanel | null;
  pause_floor_pass_rate?: number | null;
  pause_min_verdicts?: number | null;
  reasoning_budget_tokens?: number | null;
  reasoning_max_effort?: string | null;
  redact?: boolean;
  shadow_model?: string | null;
  target_model?: string | null;
  traffic_pct?: number | null;
  workflow?: RouteWorkflow | null;
};

export type RouteConditions = {
  content_type?: string | null;
  estimated_cost_gt?: number | null;
  estimated_cost_lt?: number | null;
  has_audio?: boolean | null;
  has_documents?: boolean | null;
  has_images?: boolean | null;
  input_tokens_gt?: number | null;
  input_tokens_lt?: number | null;
  model_in?: Array<string>;
  not_reasoning_class?: boolean;
  prompt_contains_any_of?: Array<string>;
  tag_equals?: string | null;
  upstream_latency_ms_p95_gt?: number | null;
};

export type RoutePanel = {
  arbiter?: string | null;
  max_cost_usd?: number | null;
  members?: Array<string>;
  quorum?: number | null;
  strategy: string;
};

export type RouteWorkflow = {
  max_cost_usd?: number | null;
  mode?: string | null;
  workflow_id: string;
};

export type SampleScore = {
  reason: string;
  request_id: string;
  verdict: JudgeVerdict;
};

export type VcrReceipt = {
  model: string;
  org_id: string;
  route: string;
  savings_usd: number;
  schema_version: 1;
  signature: string;
  token_delta: number;
  trace_id: string;
  ts: string;
  verifying_key_hex: string;
  [key: string]: unknown;
};

export type L2Receipt = {
  baseline_cost_usd: number;
  matched_entry_id: string;
  org_id: string;
  schema_version: 1;
  served_cost_usd: number;
  signature: string;
  similarity: number;
  trace_id: string;
  ts: string;
  verdict: "confident" | "verified" | "unverifiable" | "rejected";
  verifying_key_hex: string;
  [key: string]: unknown;
};

export type WfrReceipt = {
  baseline_micros: number;
  baseline_usd?: number | null;
  canonical_version: "v1" | "v2" | "v3" | "v4";
  cost_micros: number;
  cost_usd?: number | null;
  org_id: string;
  quality_verdict?: string | null;
  request_delta_eligible_requests?: number | null;
  request_delta_formula_version?: string | null;
  request_delta_measured_requests?: number | null;
  run_id: string;
  saved_micros: number;
  saved_usd?: number | null;
  signature_hex: string;
  signed_at?: string | null;
  signed_request_delta_micros?: number | null;
  signed_request_delta_usd?: number | null;
  status: string;
  verifying_key_hex: string;
  workflow_id: string;
  [key: string]: unknown;
};

export type AgentRunReceipt = {
  baseline_micros: number;
  baseline_usd?: number | null;
  canonical_version: "v1" | "v2";
  cost_micros: number;
  cost_usd?: number | null;
  org_id: string;
  request_delta_eligible_requests?: number | null;
  request_delta_formula_version?: string | null;
  request_delta_measured_requests?: number | null;
  run_id: string;
  saved_micros: number;
  saved_usd?: number | null;
  signature_hex: string;
  signed_at?: string | null;
  signed_request_delta_micros?: number | null;
  signed_request_delta_usd?: number | null;
  status: string;
  verifying_key_hex: string;
  [key: string]: unknown;
};

export type SavingsBundle = {
  attestation?: BundleAttestation | null;
  created_at: string;
  expected_result: PlanResult;
  plan_input: PlanInput;
  schema_version: 1;
  tool_version: string;
  [key: string]: unknown;
};

export type SignedReceipt = VcrReceipt | L2Receipt | WfrReceipt | AgentRunReceipt;
